<html>

<!-- Head -->
<?php view('partials/head', compact('title', 'base_url', 'version')); ?>

<body>
    <section class="not-found">
        <section class="inner">
            <h1>404</h1>
            <h3><?= get_lang('not_found', 'Page not found'); ?></h3>
            <a href="">
                <i class="fas fa-chevron-left"></i>
                <?= get_lang('back', 'Back to docs'); ?>
            </a>
        </section>
    </section>

    <!-- Scripts -->
    <?php view('partials/scripts'); ?>
</body>

</html>