<html>

<!-- Head -->
<?php view('partials/head', compact('title', 'base_url', 'version')); ?>

<body>
    <section class="layout">
        <!-- Mobile header -->
        <?php view('partials/header', compact('version', 'application', 'git')); ?>

        <!-- Edit on GitHub button -->
        <?php if (!empty($git)) : ?>
            <section class="edit">
                <a href="<?= $git; ?>" target="_blank">
                    <i class="fas fa-pencil-alt"></i>
                    <span>
                        <?= get_lang('edit_page', 'Edit this page'); ?><br>
                        <strong><?= get_lang('github', 'on GitHub'); ?></strong>
                    </span>
                </a>
            </section>
        <?php endif; ?>

        <!-- Sidenav menu -->
        <?php view('partials/menu', compact('version', 'last_version', 'version_list', 'menu')); ?>

        <!-- Content -->
        <section class="content">
            <?= $content; ?>

            <!-- Copyright -->
            <?php view('partials/copyright'); ?>
        </section>
    </section>

    <!-- Scripts -->
    <?php view('partials/scripts'); ?>
</body>

</html>