<html>

<!-- Head -->
<?php view('partials/head', compact('title', 'base_url', 'version')); ?>

<body>
    <section class="layout">
        <!-- Mobile header -->
        <?php view('partials/header', compact('version', 'application', 'git')); ?>

        <!-- Sidenav menu -->
        <?php view('partials/menu', compact('version', 'last_version', 'version_list', 'menu', 'search')); ?>

        <!-- Content -->
        <section class="content">
            <h1><?= get_lang('search_results', 'Search Results'); ?></h1>
            <h6><?= get_lang('searching_for', 'Searching for:'); ?> <?= htmlspecialchars($search); ?></h6>

            <!-- Search results -->
            <?php foreach ($results as $key => $item) : ?>
                <div class="item">
                    <h5><a href="<?= $item['url']; ?>"><?= $item['title']; ?></a></h5>
                    <?php foreach ($item['results'] as $result) : ?>
                        <p><?= strip_tags($result); ?></p>
                    <?php endforeach; ?>
                </div>
                <?php if ($key !== count($results) - 1): ?>
                    <hr>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Empty message -->
            <?php if (empty($results)) : ?>
                <?= get_lang('no_results', 'No results found.'); ?>
            <?php endif; ?>

            <!-- Copyright -->
            <?php view('partials/copyright'); ?>
        </section>
    </section>

    <!-- Scripts -->
    <?php view('partials/scripts'); ?>
</body>

</html>